# Generated by Django 4.2 on 2023-05-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0005_alter_cart_unique_together_cartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LittlelemonAPI.cart')),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carditems', to='LittlelemonAPI.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
