# Generated by Django 4.2 on 2023-05-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0007_cart_menuitem_cart_quantity_delete_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LittlelemonAPI.cart')),
            ],
        ),
    ]
