# Generated by Django 4.2 on 2023-05-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0015_remove_orderitem_price_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
