# Generated by Django 4.2 on 2023-05-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0006_cartitems_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carditems', to='LittlelemonAPI.menuitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
